### PR TITLE
Allow passing custom difficulty function to the Pool class

### PR DESCRIPTION
**Pull request by ppolewicz**
Our poll will feature, among other things, a custom difficulty adjustment function. The default one may be good for most cases, but we'd like to alter it a little bit. At the same time, we don't want to move too far away from the reference implementation - thus we'd like to have a way of providing not just our custom `pool_store`, but also the difficulty adjustment function for the pools that we create. This 5 LOC PR provides such possibility.

### CODE REVIEW

**Review by mariano54 — CHANGES_REQUESTED** [review]
Thank you for making a PR. 
That makes sense. But this current PR breaks the codebase. It will not work since you need to pass in the function when instantiating the Pool object. Please fix this.

**Comment by ppolewicz** [comment]
@mariano54 `get_new_difficulty` is used as default value for the new constructor parameter, so it maintains backward compatibility. Did I miss something?

**Comment by mariano54** [comment]
Thank you, I missed that default value! LGTM.
Have you ran this to make sure it works?

**Review by mariano54 — APPROVED** [review]

**Comment by ppolewicz** [comment]
We have not ran it, but the patch is extremely compact and we think any regression, however improbable, will be easily detected by an integration/system test. Is that ok?

We plan to contribute a couple of larger changes next week and I don't think we'll get away with the lack of test environment there :)

**Comment by mariano54** [comment]
Yep, sounds good!

**Pull request merged**
