### PR TITLE
Adjust difficulty at least once a day (time_target).

### LINKED ISSUE #193: Very rare recalc of difficulty if difficulty set high.
Currently difficulty is lowered in 2 cases:
1. There were no partials for 1 hour.
2. When target number of partials reached.

In the scenario when farmer generates one partial, lets say every 30 minutes he will be able to accumulate number_of_partials_target in more than 6 days, so he will get less than 50 partials in 24 hours - much less than target 300 in 24 hours.

### PR DESCRIPTION
**Pull request by lemur73**
closes #193

### CODE REVIEW

**Review by mariano54 — CHANGES_REQUESTED** [review]
Can you add a test for this? Note that there are tests for this method in the tests directory.

**Comment by lemur73** [comment]
> Can you add a test for this? Note that there are tests for this method in the tests directory.

Updated.
BTW, there is another problem with this function

```
      if len(recent_partials) == 0:
          return current_difficulty

```
This means, that if difficult gets too high and farmer is not able to produce partial with this difficulty then he stuck for a while not able to get any points.
IMHO, time should be measured from the connection or previous difficulty adjustment attempt.

**Comment by lemur73** [comment]
> Can you add a test for this? Note that there are tests for this method in the tests directory.

Fixed

**Review by mariano54 — APPROVED** [review]
Thank you for your changes

**Pull request merged**
