### PR TITLE
Bug Fix: Inaccurate points update！

### PR DESCRIPTION
**Pull request by pchacker**
farmer request pool "post_farmer", "put_farmer" RPC interface, causing points to be replace by historical data.

### CODE REVIEW

**Comment by mariano54** [comment]
Looks good! Have you tested this change?

**Comment by pchacker** [comment]
Yes, it has been running in my pool for 3 months now.

**Comment by chrishp** [comment]
Might be clearer to separate into store.update_farmer and store.add_farmer; since by the time you arrive there you should already know whether farmer exist or not.

**Comment by mariano54** [comment]
We also need to do this change for the mariaDB store as well. If anyone has free time, please take this ticket . 

https://github.com/Chia-Network/pool-reference/issues/251

**Review by mariano54 — APPROVED** [review]

**Comment by jack60612** [comment]
> We also need to do this change for the mariaDB store as well. If anyone has free time, please take this ticket .
> 
> #251

does not need to be fixed for maria as there is already an ON DUPLICATE KEY UPDATE  which basically does the same thing while being more efficient

**Comment by jack60612** [comment]
Tested in prod and works fine @mariano54

**Pull request merged**
