### PR TITLE
Turn relative lock height down to 10 for testing

### PR DESCRIPTION
**Pull request by aqk**

### CODE REVIEW

**Review by Quexington — APPROVED** [review]
I think this should be much lower by default as well imo.

**Comment by xdustinface** [comment]
@aqk Let's maybe just add it to the config?

**Comment by mariano54** [comment]
Sorry i forgot to change that before! it's a useful change

**Comment by aqk** [comment]
Yes, we should add it to the config. We also need a comment next to it in the config similar to what's in the source code.

**Comment by mariano54** [comment]
Fixed in main

**Pull request closed without merging**
