### PR TITLE
Factoring out payment manager

### PR DESCRIPTION
**Pull request by mpnowacki-reef**
This solves https://github.com/Chia-Network/pool-reference/issues/132

### CODE REVIEW

**Comment by mpnowacki-reef** [comment]
misclick

**Comment by mpnowacki-reef** [comment]
@mariano54 Would you like to ask some questions/clear something up about this PR?

**Comment by mpnowacki-reef** [comment]
I've added small changes to allow for usage of various customizations without having to rewrite `start_pool_server` - including the already merged `login_response`.

**Comment by mariano54** [comment]
I like the idea, and the changes make sense. I haven't reviewed it in detail yet though. I also have not tested the code on testnet. Have you ran this / have you been running this on testnet or mainnet yet?

**Comment by mpnowacki-reef** [comment]
I wasn't able to test the `collect_rewards_loop` properly, because I wasn't able to win anything, but I did test the `create_payment_loop` with only slight mockery and `submit_payment_loop` with no mocking.

**Comment by xdustinface** [comment]
Needs rebase

**Comment by ppolewicz** [comment]
@xdustinface I think Michał is on vacation, so I just did a merge with github interface - the conflict was mostly in the imports + one line which I think was a bug fixed a few days ago on `main` which happened to be close to the changes in this PR. I think it should be good to go.

**Comment by mpnowacki-reef** [comment]
@xdustinface @mariano54 I can resolve conflicts again, but will you merge it after that?

**Comment by jack60612** [comment]
@mpnowacki-reef would you like to merge your pull with mine as we both kinda did the same thing #232 .  I Made the  payment system completely enableable / disableable so you can run multiple endpoints behind a load balancer and not run the payment system on every one which would be bad. Let me know what you think - Jack

**Comment by mpnowacki-reef** [comment]
@jack60612 Yes, enabling/disabling the payment manager would suffice for many use cases. I introduce several other fixes/improvements in this PR, and i guess these are worth salvaging. Namely: 
* fixing of the pass-through for the custom difficulty function
* custom PoolServer class
* StateKeeper to avoid repeating code and divide responsibilities a bit more

What do you think about that?

**Comment by jack60612** [comment]
> @jack60612 Yes, enabling/disabling the payment manager would suffice for many use cases. I introduce several other fixes/improvements in this PR, and i guess these are worth salvaging. Namely:
> 
> * fixing of the pass-through for the custom difficulty function
> * custom PoolServer class
> * StateKeeper to avoid repeating code and divide responsibilities a bit more
> 
> What do you think about that?

the way you do it is 100% better 
i think @mariano54 is moving so wait till he gets back to fix the merge conflicts.
but ill build my pull on yours happily when it gets committed until then ill just wait lol.

**Comment by jack60612** [comment]
@mariano54 i heard your back. @mpnowacki-reef if possible could you fix the merging issue now?

**Comment by ppolewicz** [comment]
If Mariano is back and intends to merge then sure, we'll fix the merging issues. Please confirm.

**Comment by mariano54** [comment]
I can merge it, since it's mostly a moving of code, and not a lot of new coded is added. Please fix the merge conflicts though.

**Comment by mariano54** [comment]
I apologize for the long delay. We have decided not to merge in order to keep lines of code smaller. It is a reference so we don't need the generality and power that this PR provides. Thanks for the work.

**Comment by unsocial-bleach** [comment]
It would be a mistake not to merge this. The reference should be as complete as possible.

**Pull request closed without merging**
