### PR TITLE
CHIA-992: Update pool reference code to be compatible with chia-blockchain 2.4.2

### PR DESCRIPTION
**Pull request by aqk**

### CODE REVIEW

**Review by altendky — CHANGES_REQUESTED** [review]
Remove new empty file `tests/test_partial_validation.py`?

**Review by Quexington — DISMISSED** [review]
This seems fine to me but so many of these changes are _so_ old I think we should consider deprecating this repo if no one noticed this until now.

**Comment by aqk** [comment]
> Remove new empty file `tests/test_partial_validation.py`?

Thanks, ya.

**Comment by aqk** [comment]
> This seems fine to me but so many of these changes are _so_ old I think we should consider deprecating this repo if no one noticed this until now.

Earle really wanted to deprecate the repo, but then he reasoned "what if we run into an issue with pooling (which we maintain), and have to fix this before we can even repro the problem?"

Your argument that these changes are very old is a good argument to move the code into the main repo.

**Comment by emlowe** [comment]
> This seems fine to me but so many of these changes are _so_ old I think we should consider deprecating this repo if no one noticed this until now.

I went back and forth on this myself - but my current rationale is that we do need a way to be able to test the pool features of the wallet from time to time and we can't always rely on pools running testnet instances - and doing the testing on mainnet can be complicated as well. So there is some value in being able to test the wallet features with a nominally working testnet pool server.

There have been some occasional comments in discord that this repo wasn't up to date, so it was noticed by that small group of users who run pools.

**Review by emlowe — CHANGES_REQUESTED** [review]
Remove empty `test_partial_validation.py`

**Comment by Quexington** [comment]
> we do need a way to be able to test the pool features of the wallet from time to time
If this is the whole rationale then we should at least maybe put effort into stripping this down to the simplest possible pooling client.  Like it doesn't even need to run a loop scanning for rewards, the DB can be in memory, etc.  We can then cut down on complexity and hopefully dependencies and exposure to the `chia-blockchain` source "library" code.

**Review by emlowe — APPROVED** [review]

**Pull request merged**
