### PR TITLE
Lots of new features + full repo code cleanup to align with PEP 8

### PR DESCRIPTION
**Pull request by jack60612**
Leave any suggestions below as i forked there source and i want to see if anything good can from from them shutting down.

Waiting for #142

### CODE REVIEW

**Comment by ppolewicz** [comment]
nice things I can see are:
- postgres store
- payment record registry
- harvester id in partial records
- point/capacity snapshots
- payout/reward tracking

**Comment by jack60612** [comment]
im going to start removing the maxio branding now

**Comment by Comput3rSaysNo** [comment]
This seems to be the source code from "maxipool" (without O)

**Comment by jack60612** [comment]
lol its still being updated

**Comment by jack60612** [comment]
> This seems to be the source code from "maxipool" (without O)

thanks!

**Comment by jack60612** [comment]
I finally had time to look at the code thoroughly. The postgres code is ehh at best but the rest of the features have been cleaned up and implemented. If you have time a review would be nice lol @ppolewicz .
But everything is mostly done

**Comment by jack60612** [comment]
I'm going to most likely include the postgres code in #191 when it is ready. and remove it from here

**Comment by jack60612** [comment]
im going to make some adjustments to be compatible with #142 when it gets committed

**Pull request closed without merging**
